puts "1.) Buy Milk"
puts "2.) Buy Cheese"
puts "3.) Learn Ruby"
puts "4.) Feed the cats"
puts "5.) Register for conference (conference)"
puts "6.) Book hotel (conference)"
puts "7.) Book flight (conference)"
puts "8.) Rent a car (conference)"
puts "9.) Research ninjitsu"
